### ISSUE TITLE
RMD Fatal Error [ran it once]

### ISSUE THREAD

**Issue by NandaKumar8776** [shadowmoose/RedditDownloader#104]
### Describe the bug
RMD Fatal Error

### Environment Info
 -  Windows 10
 - RMD Version: "3.0.0"

### Screenshots/Information
λ python run.py
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44) [MSC v.1916 64 bit (AMD64)] on win32
Updating requirements. This may take a while on first-time installs..
'module' object is not callable

====================================
   Reddit Media Downloader 3.0.0
====================================
    (By ShadowMoose @ Github)

Loaded settings file [C:\Users\xXxN30NxXx\AppData\Local\RedditDownloader\RMD\settings.json].
Traceback (most recent call last):
  File "run.py", line 59, in <module>
    rmd.run()
  File "C:\Users\xXxN30NxXx\Desktop\Automate\RedditDownloader\redditdownloader\__main__.py", line 147, in run
    sql.init_from_settings()
  File "C:\Users\xXxN30NxXx\Desktop\Automate\RedditDownloader\redditdownloader\sql\__init__.py", line 60, in init_from_settings
    init(db_file.absolute())
  File "C:\Users\xXxN30NxXx\Desktop\Automate\RedditDownloader\redditdownloader\sql\__init__.py", line 53, in init
    _run_migrations(session())
  File "C:\Users\xXxN30NxXx\Desktop\Automate\RedditDownloader\redditdownloader\sql\__init__.py", line 124, in _run_migrations
    _check_legacy(conn)
  File "C:\Users\xXxN30NxXx\Desktop\Automate\RedditDownloader\redditdownloader\sql\__init__.py", line 147, in _check_legacy
    if not context.get_current_revision():
  File "C:\Users\xXxN30NxXx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\alembic\runtime\migration.py", line 390, in get_current_revision
    "please use get_current_heads()" % self.version_table
alembic.util.exc.CommandError: Version table 'alembic_version' has more than one head present; please use get_current_heads()

Caught a fatal error running RMD. Cannot continue.
-Press [Enter] to quit- 

### Additional context
I ran RMD once and i saw the GUI of RMD. but then, i had to close it due to other reasons. after then when i tried to open it again, but then it showed this error. i am running it on CMDER on windows 10. i am not much of a code geek so please do let me know how to solve it.

**Comment by shadowmoose** [comment]
The latest version in the master tree should hopefully have a fix for this. If you would like to test it, try deleting the manifest "sqlite" file generated in the download directory, then relaunching with the latest version.

**Comment by shadowmoose** [comment]
Resolved as of [Release 3.0.0](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.0.0). Feel free to reopen if this still needs more attention.
