### ISSUE TITLE
"Fatal error" on startup

### ISSUE THREAD

**Issue by Riftero** [shadowmoose/RedditDownloader#111]
Ran the app for the first time -> changed the desired download directory -> verified my username 
Then i tried to download my saved posts& comments and it didnt work, i tried different filters& sources and i still got 0 files scanned or downloaded
Closed the app and when i tried to reopen it it gave me an error
Traceback (most recent call last):
  File "Run.py", line 177, in <module>
  File "redditdownloader\__main__.py", line 149, in run
  File "redditdownloader\sql\__init__.py", line 60, in init_from_settings
  File "redditdownloader\sql\__init__.py", line 53, in init
  File "redditdownloader\sql\__init__.py", line 124, in _run_migrations
  File "redditdownloader\sql\__init__.py", line 144, in _check_legacy
  File "site-packages\sqlalchemy\orm\session.py", line 1278, in execute
  File "site-packages\sqlalchemy\engine\base.py", line 982, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
  File "site-packages\sqlalchemy\util\compat.py", line 152, in reraise
  File "site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT name FROM sqlite_master WHERE type="table" AND name="posts";]
(Background on this error at: http://sqlalche.me/e/4xp6)

Caught a fatal error running RMD. Cannot continue.
-Press [Enter] to quit-

**Comment by shadowmoose** [comment]
Hey, sorry, I missed this when it was posted. If you're still stuck, I'd suggest deleting the `manifest.sqlite` database file RMD created in the download directory. It seems that something has corrupted it.
