### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by BobMacpherson** [shadowmoose/RedditDownloader#115]
### Describe the bug
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/path/to/RedditDownloader/redditdownloader/processing/redditloader.py", line 30, in run
    self.load()
  File "/path/to/RedditDownloader/redditdownloader/processing/redditloader.py", line 49, in load
    self._scan_sources()
  File "/path/to/RedditDownloader/redditdownloader/processing/redditloader.py", line 63, in _scan_sources
    for r in source.get_elements():
  File "/path/to/RedditDownloader/redditdownloader/sources/subreddit_posts_source.py", line 12, in get_elements
    for p in reddit.subreddit_posts(
  File "/path/to/RedditDownloader/redditdownloader/static/praw_wrapper.py", line 131, in subreddit_posts
    yield from _praw_apply_filter(_reddit.subreddit(sub), order_by, limit, time)
  File "/path/to/RedditDownloader/redditdownloader/static/praw_wrapper.py", line 196, in _praw_apply_filter
    assert time in time_filters()
AssertionError
### Environment Info
 - **ArchLinux** 
 - **Python:3.8.1** 
 - **RMD Version:5cff780** 

### Additional context
Version 2.01,the command line only version, has no problems downloading the same subs from Reddit.

**Comment by CDestructor12** [comment]
In the last version it dosent work, just closes itself when i try to open it. Windows 10

**Comment by shadowmoose** [comment]
Ah, just noticed that I missed this one. For this issue I would need to know more about the config setup. I cannot replicate this in any testing.

**Comment by CDestructor12** [comment]
> Ah, just noticed that I missed this one. For this issue I would need to know more about the config setup. I cannot replicate this in any testing.

Im in Windows 10 version 10.0.0.19041 build 19041
