### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by chalupas** [shadowmoose/RedditDownloader#131]
### Describe the bug
Error when running .exe

### Environment Info
Windows 10
3.0.1

### Screenshots/Information
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit
(AMD64)] on win32
Checking for a standalone release update for platform windows...

====================================
   Reddit Media Downloader 3.0.1
====================================
    (By ShadowMoose @ Github)

Loaded settings file [C:\Users\user\AppData\Local\RedditDownloader\RMD\settings.
json].
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 2285, in _wrap_pool_conne
ct
  File "site-packages\sqlalchemy\pool\base.py", line 363, in connect
  File "site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
  File "site-packages\sqlalchemy\pool\base.py", line 492, in checkout
  File "site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
  File "site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
  File "site-packages\sqlalchemy\pool\base.py", line 437, in __init__
  File "site-packages\sqlalchemy\pool\base.py", line 657, in __connect
  File "site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\pool\base.py", line 652, in __connect
  File "site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
  File "site-packages\sqlalchemy\engine\default.py", line 490, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Run.py", line 177, in <module>
  File "redditdownloader\__main__.py", line 149, in run
  File "redditdownloader\sql\__init__.py", line 60, in init_from_settings
  File "redditdownloader\sql\__init__.py", line 52, in init
  File "redditdownloader\sql\__init__.py", line 65, in _create
  File "site-packages\sqlalchemy\orm\session.py", line 1277, in execute
  File "site-packages\sqlalchemy\orm\session.py", line 1139, in _connection_for_
bind
  File "site-packages\sqlalchemy\orm\session.py", line 432, in _connection_for_b
ind
  File "site-packages\sqlalchemy\engine\base.py", line 2251, in _contextual_conn
ect
  File "site-packages\sqlalchemy\engine\base.py", line 2289, in _wrap_pool_conne
ct
  File "site-packages\sqlalchemy\engine\base.py", line 1555, in _handle_dbapi_ex
ception_noconnection
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 2285, in _wrap_pool_conne
ct
  File "site-packages\sqlalchemy\pool\base.py", line 363, in connect
  File "site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
  File "site-packages\sqlalchemy\pool\base.py", line 492, in checkout
  File "site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
  File "site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
  File "site-packages\sqlalchemy\pool\base.py", line 437, in __init__
  File "site-packages\sqlalchemy\pool\base.py", line 657, in __connect
  File "site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\pool\base.py", line 652, in __connect
  File "site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
  File "site-packages\sqlalchemy\engine\default.py", line 490, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open datab
ase file
(Background on this error at: http://sqlalche.me/e/e3q8)

Caught a fatal error running RMD. Cannot continue.
-Press [Enter] to quit-

### Additional context
I last successfully ran it last week.

**Comment by shadowmoose** [comment]
Looks like either the database is corrupted in some way, still in use by another RMD instance, or in a location RMD does not have permission to write (unlikely on Windows). If you have access to a SQLite editor, such as https://sqlitebrowser.org/, you can try opening the database file with that and seeing if it's locked. If you just want to start from scratch, you can also delete or rename to database file, then relaunch RMD.

**Comment by chalupas** [comment]
I believe last time I ran RMD I had to shutdown ungracefully so its plausible it thinks its sill in use by another instance. Wheres the location of the database file on windows?

**Comment by chalupas** [comment]
I found the manifest.sqllite file in the download directory and moved it elsewhere. When I run the program now it get the following error :


Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit
(AMD64)] on win32
Checking for a standalone release update for platform windows...

====================================
   Reddit Media Downloader 3.0.1
====================================
    (By ShadowMoose @ Github)

Loaded settings file [C:\Users\user\AppData\Local\RedditDownloader\RMD\settings.
json].
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 2285, in _wrap_pool_conne
ct
  File "site-packages\sqlalchemy\pool\base.py", line 363, in connect
  File "site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
  File "site-packages\sqlalchemy\pool\base.py", line 492, in checkout
  File "site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
  File "site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
  File "site-packages\sqlalchemy\pool\base.py", line 437, in __init__
  File "site-packages\sqlalchemy\pool\base.py", line 657, in __connect
  File "site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\pool\base.py", line 652, in __connect
  File "site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
  File "site-packages\sqlalchemy\engine\default.py", line 490, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Run.py", line 177, in <module>
  File "redditdownloader\__main__.py", line 149, in run
  File "redditdownloader\sql\__init__.py", line 60, in init_from_settings
  File "redditdownloader\sql\__init__.py", line 52, in init
  File "redditdownloader\sql\__init__.py", line 65, in _create
  File "site-packages\sqlalchemy\orm\session.py", line 1277, in execute
  File "site-packages\sqlalchemy\orm\session.py", line 1139, in _connection_for_
bind
  File "site-packages\sqlalchemy\orm\session.py", line 432, in _connection_for_b
ind
  File "site-packages\sqlalchemy\engine\base.py", line 2251, in _contextual_conn
ect
  File "site-packages\sqlalchemy\engine\base.py", line 2289, in _wrap_pool_conne
ct
  File "site-packages\sqlalchemy\engine\base.py", line 1555, in _handle_dbapi_ex
ception_noconnection
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 2285, in _wrap_pool_conne
ct
  File "site-packages\sqlalchemy\pool\base.py", line 363, in connect
  File "site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
  File "site-packages\sqlalchemy\pool\base.py", line 492, in checkout
  File "site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
  File "site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
  File "site-packages\sqlalchemy\pool\base.py", line 437, in __init__
  File "site-packages\sqlalchemy\pool\base.py", line 657, in __connect
  File "site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\pool\base.py", line 652, in __connect
  File "site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
  File "site-packages\sqlalchemy\engine\default.py", line 490, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open datab
ase file
(Background on this error at: http://sqlalche.me/e/e3q8)


Caught a fatal error running RMD. Cannot continue.
-Press [Enter] to quit-

**Comment by shadowmoose** [comment]
Is the output directory for RMD on your standard Windows filesystem? The Python library for SQLite isn't able to open a database file in the given save location. I'm not sure why exactly this is happening for you, since apparently it worked at one point. 

I'm going to try and hunt this down, but so far I cannot replicate this problem.

**Comment by chalupas** [comment]
The output directory was NOT on my windows system. That was the issue. I changed it to a network drive at one point and forgot during a bunch of other computer issues. I changed back to the local directory by editing settings.json and its working again. My apologies!

**Comment by shadowmoose** [comment]
No problem, I'll need to document that somewhere - the SQLite database RMD uses (the "manifest" file) won't work properly on some file systems (mostly remote ones) because it cannot exclusively lock the file for reading/writing.

Thanks for the feedback. This will hopefully be useful for other uses hitting similar issues.
