### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by IamarockIamanisland** [shadowmoose/RedditDownloader#138]
### Describe the bug
Apologies if this is a common mistake and I'm just being dumb. RMD does not start a scan. It simply shows the download screen for a split second, showing the download threads, and then stopping. When I reran it, it showed that filed found equaled 0, and that it was searching "null." When restarting the program, as shown below, it displays a list of errors

### Environment Info
 - **OS:** Windows 10
 - **RMD Version:** 3.0.1
 - **Browser:** Brave

### Console log
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win64
Checking for a standalone release update for platform windows...

====================================
   Reddit Media Downloader 3.0.1
====================================
    (By ShadowMoose @ Github)

Loaded settings file [C:\Users\user\AppData\Local\RedditDownloader\RMD\settings.json].
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1284, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Run.py", line 177, in <module>
  File "redditdownloader\__main__.py", line 149, in run
  File "redditdownloader\sql\__init__.py", line 60, in init_from_settings
  File "redditdownloader\sql\__init__.py", line 53, in init
  File "redditdownloader\sql\__init__.py", line 124, in _run_migrations
  File "redditdownloader\sql\__init__.py", line 144, in _check_legacy
  File "site-packages\sqlalchemy\orm\session.py", line 1292, in execute
  File "site-packages\sqlalchemy\engine\base.py", line 1020, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1324, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1518, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1284, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT name FROM sqlite_master WHERE type="table" AND name="posts";]
(Background on this error at: http://sqlalche.me/e/4xp6)

Caught a fatal error running RMD. Cannot continue.
-Press [Enter] to quit-

**Comment by shadowmoose** [comment]
It looks like somehow your manifest file got corrupted. This can happen often if the storage location is on a network or remote location. If this is not the case, try deleting the manifest file stored in the download directory for RMD, then relaunch.

**Comment by IamarockIamanisland** [comment]
That seemed to have fixed it. However, when I run it, it ran for a couple of seconds before turning off. Trying to run it again gave me the same issue.

**Comment by shadowmoose** [comment]
I'm not sure what the cause could be here. The manifest database should be stable on any local hard drive. If you're getting a new error in the console, can you share it here?

**Comment by IamarockIamanisland** [comment]
"Process RedditElementLoader:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "redditdownloader\processing\redditloader.py", line 30, in run
  File "redditdownloader\processing\redditloader.py", line 49, in load
  File "redditdownloader\processing\redditloader.py", line 63, in _scan_sources
  File "redditdownloader\sources\subreddit_posts_source.py", line 16, in get_elements
  File "redditdownloader\static\praw_wrapper.py", line 131, in subreddit_posts
  File "redditdownloader\static\praw_wrapper.py", line 202, in _praw_apply_filter
  File "site-packages\praw\models\reddit\base.py", line 34, in __getattr__
  File "site-packages\praw\models\reddit\base.py", line 37, in __getattr__
AttributeError: 'Subreddit' object has no attribute 'best'
Searching posts: ['author', 'type', 'title', 'body', 'subreddit', 'source_alias']  25 0
returned: 25"

I'd like to apologize for not giving you much to work with. But yeah, this is what is outputted to the console when I run it.

**Comment by shadowmoose** [comment]
Hmm, it looks like finding the "best" submissions is currently broken. I'm not sure if this is actually supported by the Reddit API at this point. 

I'll patch this with some code to fix this bug for any other users, but I'd suggest reconfiguring your sources to not use "best".

**Comment by IamarockIamanisland** [comment]
Thank you so much for responding to me. I hope it's an easy fix.
