### ISSUE TITLE
Exceptions with installing requirements (RedditDounloader)

### ISSUE THREAD

**Issue by stevedock** [shadowmoose/RedditDownloader#14]
First of all thanks for putting together this script! This is exactly what I am looking to use for a school project. 

When I ran the pip install -r requirements.txt command I get the following output towards the bottom of the list: 

**Exception:
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\program files (x86)\python36-32\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\python36-32\\Lib\\site-packages\\certifi'**

All of this text is in red and the main.py script will not run because it can't locate a module. 
An ideas on what is causing the requirements to not install properly?
thanks, Steve

**Comment by shadowmoose** [comment]
It appears as though you cannot update your libraries with the current user's permissions. Try launching a console as the Administrative user, then rerunning the installation.
