### ISSUE TITLE
RMD locks when searching a reddit account that has been suspended.

### ISSUE THREAD

**Issue by Truman-D** [shadowmoose/RedditDownloader#147]
**Steps to Reproduce:**
1. Take a working setup of RMD with a working Source
2. Find a reddit user who has been suspended.
3. Add a Source of type "user-posts-source" [I also had the same user listed in a source of type "pushshift-user-source"] for the suspended user, say "UserFoobar"
4. Save and Start Downloading.
**Result:**
Downloads will start normally, but when it gets to scanning the suspended user RMD will lock displaying:
```
Download Progress
Scanning for Posts
Files Found: 12345 (searching "UserFoobar")		
```
At the same time the RMD Console displayed the following error (may not be connected, just last event logged):
```
Process RedditElementLoader:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "redditdownloader\processing\redditloader.py", line 30, in run
    self.load()
  File "redditdownloader\processing\redditloader.py", line 51, in load
    self.progress.set_scanning(False)
  File "redditdownloader\processing\redditloader.py", line 65, in _scan_sources
    return
  File "redditdownloader\sources\user_posts_source.py", line 14, in get_elements
    find_comments=self.data['scan_comments']):
  File "redditdownloader\static\praw_wrapper.py", line 144, in user_posts
    if find_comments:
  File "site-packages\praw\models\listing\generator.py", line 61, in __next__
  File "site-packages\praw\models\listing\generator.py", line 71, in _next_batch
  File "site-packages\praw\reddit.py", line 490, in get
  File "site-packages\praw\reddit.py", line 574, in _objectify_request
  File "site-packages\praw\reddit.py", line 732, in request
  File "site-packages\prawcore\sessions.py", line 336, in request
  File "site-packages\prawcore\sessions.py", line 265, in _request_with_retries
prawcore.exceptions.Forbidden: received 403 HTTP response
```
It will stay locked like this and will never finish the scan. A manual shutdown of RMD and then removing the offending user "UserFoobar" source will restore normal operation and scan's can complete again without error.

Windows 10 Pro
RMD 3.1.0

This looks to be caused by the fact that "UserFoobar" has had their account suspended.
Visiting their Profile URL:
https://www.reddit.com/user/UserFoobar

Displays the following error:
```
This account has been suspended .
GO HOME
```

**Comment by shadowmoose** [comment]
I hadn't run into this before. Should be a simple enough fix.

Thanks for the detailed report.

**Comment by MaeInHeels** [comment]
Any updates on this? I generated sources for a list of about 100 users and imported them the `settings.json` file, but a few of these users were suspended, so I had to check all of them manually so I could remove the pertaining sources. Since users may also become unsuspended, deleting the source altogether isn't an ideal solution.

**Comment by shadowmoose** [comment]
Sorry about that, forgot about this issue when I started a larger rewrite. It's simple enough to fix, so I've rolled out a patch that's been deployed as [RMD 3.1.3](https://github.com/shadowmoose/RedditDownloader/releases/tag/3.1.3).
