### ISSUE TITLE
Can't download anything and RMD wont open again

### ISSUE THREAD

**Issue by parasiteoflife** [shadowmoose/RedditDownloader#150]
### Describe the bug
Made a test group with a single subreddit using pushshift and after detecting the amount of files, RedditDownloader does nothing and I got errors on the console, I can't even cancel the download so what I can only do is ctrl+c. Now after reopening RedditDownloader it closes itself and throws the same error.
This is the first time I ever use RedditDownloader.

### Environment Info
 - **OS:** Windows 10
 - **RMD Version:** 3.1.0

### Additional context

Here is the log:

```
Started downloader.
        +Activated WAL Mode.
Database is not up to date! None < 6f8cfc06eaa3
Versioning pre-alembic < 3.0.0 DB.
        +Upgraded manifest to version 6f8cfc06eaa3
Database is not up to date! f8035abd1974 < 6f8cfc06eaa3
Database is not up to date! f8035abd1974 < 6f8cfc06eaa3
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlite3.OperationalError: table hashes already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "redditdownloader\sql\__init__.py", line 140, in _run_migrations
  File "site-packages\alembic\command.py", line 298, in upgrade
  File "site-packages\alembic\script\base.py", line 489, in run_env
  File "site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
  File "site-packages\alembic\util\compat.py", line 173, in load_module_py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 82, in <module>
    run_migrations_online()
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "site-packages\alembic\runtime\environment.py", line 846, in run_migrations
  File "site-packages\alembic\runtime\migration.py", line 518, in run_migrations
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\versions\6f8cfc06eaa3_add_hash_table.py", line 30, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "site-packages\alembic\operations\ops.py", line 1250, in create_table
  File "site-packages\alembic\operations\base.py", line 345, in invoke
  File "site-packages\alembic\operations\toimpl.py", line 101, in create_table
  File "site-packages\alembic\ddl\impl.py", line 252, in create_table
  File "site-packages\alembic\ddl\impl.py", line 134, in _exec
  File "site-packages\sqlalchemy\engine\base.py", line 1014, in execute
  File "site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1076, in _execute_ddl
  File "site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table hashes already exists
[SQL:
CREATE TABLE hashes (
        id INTEGER NOT NULL,
        file_id VARCHAR,
        full_hash VARCHAR,
        p1 VARCHAR,
        p2 VARCHAR,
        p3 VARCHAR,
        p4 VARCHAR,
        PRIMARY KEY (id),
        FOREIGN KEY(file_id) REFERENCES files (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Failed to upgrade database!
Rolled back file: Z:\Downloads\manifest.sqlite   From: Z:\Downloads\manifest.sqlite-bkup.sqlite
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlite3.OperationalError: table hashes already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "redditdownloader\sql\__init__.py", line 140, in _run_migrations
  File "site-packages\alembic\command.py", line 298, in upgrade
  File "site-packages\alembic\script\base.py", line 489, in run_env
  File "site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
  File "site-packages\alembic\util\compat.py", line 173, in load_module_py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 82, in <module>
    run_migrations_online()
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "site-packages\alembic\runtime\environment.py", line 846, in run_migrations
  File "site-packages\alembic\runtime\migration.py", line 518, in run_migrations
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\versions\6f8cfc06eaa3_add_hash_table.py", line 30, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "site-packages\alembic\operations\ops.py", line 1250, in create_table
  File "site-packages\alembic\operations\base.py", line 345, in invoke
  File "site-packages\alembic\operations\toimpl.py", line 101, in create_table
  File "site-packages\alembic\ddl\impl.py", line 252, in create_table
  File "site-packages\alembic\ddl\impl.py", line 134, in _exec
  File "site-packages\sqlalchemy\engine\base.py", line 1014, in execute
  File "site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1076, in _execute_ddl
  File "site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table hashes already exists
[SQL:
CREATE TABLE hashes (
        id INTEGER NOT NULL,
        file_id VARCHAR,
        full_hash VARCHAR,
        p1 VARCHAR,
        p2 VARCHAR,
        p3 VARCHAR,
        p4 VARCHAR,
        PRIMARY KEY (id),
        FOREIGN KEY(file_id) REFERENCES files (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Failed to upgrade database!
[Errno 2] No such file or directory: 'Z:\\Downloads\\manifest.sqlite-bkup.sqlite'
Process Downloader-4:
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlite3.OperationalError: table hashes already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "redditdownloader\sql\__init__.py", line 140, in _run_migrations
  File "site-packages\alembic\command.py", line 298, in upgrade
  File "site-packages\alembic\script\base.py", line 489, in run_env
  File "site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
  File "site-packages\alembic\util\compat.py", line 173, in load_module_py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 82, in <module>
    run_migrations_online()
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "site-packages\alembic\runtime\environment.py", line 846, in run_migrations
  File "site-packages\alembic\runtime\migration.py", line 518, in run_migrations
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\versions\6f8cfc06eaa3_add_hash_table.py", line 30, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "site-packages\alembic\operations\ops.py", line 1250, in create_table
  File "site-packages\alembic\operations\base.py", line 345, in invoke
  File "site-packages\alembic\operations\toimpl.py", line 101, in create_table
  File "site-packages\alembic\ddl\impl.py", line 252, in create_table
  File "site-packages\alembic\ddl\impl.py", line 134, in _exec
  File "site-packages\sqlalchemy\engine\base.py", line 1014, in execute
  File "site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1076, in _execute_ddl
  File "site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table hashes already exists
[SQL:
CREATE TABLE hashes (
        id INTEGER NOT NULL,
        file_id VARCHAR,
        full_hash VARCHAR,
        p1 VARCHAR,
        p2 VARCHAR,
        p3 VARCHAR,
        p4 VARCHAR,
        PRIMARY KEY (id),
        FOREIGN KEY(file_id) REFERENCES files (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "redditdownloader\processing\downloader.py", line 29, in run
  File "redditdownloader\sql\__init__.py", line 62, in init_from_settings
  File "redditdownloader\sql\__init__.py", line 55, in _init
  File "redditdownloader\sql\__init__.py", line 146, in _run_migrations
Exception: Failed to upgrade database!
Database is not up to date! f8035abd1974 < 6f8cfc06eaa3
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlite3.OperationalError: table hashes already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "redditdownloader\sql\__init__.py", line 140, in _run_migrations
  File "site-packages\alembic\command.py", line 298, in upgrade
  File "site-packages\alembic\script\base.py", line 489, in run_env
  File "site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
  File "site-packages\alembic\util\compat.py", line 173, in load_module_py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 82, in <module>
    run_migrations_online()
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "site-packages\alembic\runtime\environment.py", line 846, in run_migrations
  File "site-packages\alembic\runtime\migration.py", line 518, in run_migrations
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI154282\sql\alembic_files\versions\6f8cfc06eaa3_add_hash_table.py", line 30, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "site-packages\alembic\operations\ops.py", line 1250, in create_table
  File "site-packages\alembic\operations\base.py", line 345, in invoke
  File "site-packages\alembic\operations\toimpl.py", line 101, in create_table
  File "site-packages\alembic\ddl\impl.py", line 252, in create_table
  File "site-packages\alembic\ddl\impl.py", line 134, in _exec
  File "site-packages\sqlalchemy\engine\base.py", line 1014, in execute
  File "site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1076, in _execute_ddl
  File "site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table hashes already exists
[SQL:
CREATE TABLE hashes (
        id INTEGER NOT NULL,
        file_id VARCHAR,
        full_hash VARCHAR,
        p1 VARCHAR,
        p2 VARCHAR,
        p3 VARCHAR,
        p4 VARCHAR,
        PRIMARY KEY (id),
        FOREIGN KEY(file_id) REFERENCES files (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Failed to upgrade database!
Rolled back file: Z:\Downloads\manifest.sqlite   From: Z:\Downloads\manifest.sqlite-bkup.sqlite
```

When I try to open RedditDownloader again I get this:

```
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Checking for a standalone release update for platform windows...

====================================
   Reddit Media Downloader 3.1.0
====================================
    (By ShadowMoose @ Github)

Loaded settings file [C:\Users\parasiteoflife\AppData\Local\RedditDownloader\RMD\settings.json].
Database is not up to date! f8035abd1974 < 6f8cfc06eaa3
Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlite3.OperationalError: table hashes already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "redditdownloader\sql\__init__.py", line 140, in _run_migrations
  File "site-packages\alembic\command.py", line 298, in upgrade
  File "site-packages\alembic\script\base.py", line 489, in run_env
  File "site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
  File "site-packages\alembic\util\compat.py", line 173, in load_module_py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI166522\sql\alembic_files\env.py", line 82, in <module>
    run_migrations_online()
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI166522\sql\alembic_files\env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "site-packages\alembic\runtime\environment.py", line 846, in run_migrations
  File "site-packages\alembic\runtime\migration.py", line 518, in run_migrations
  File "C:\Users\parasiteoflife\AppData\Local\Temp\_MEI166522\sql\alembic_files\versions\6f8cfc06eaa3_add_hash_table.py", line 30, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "site-packages\alembic\operations\ops.py", line 1250, in create_table
  File "site-packages\alembic\operations\base.py", line 345, in invoke
  File "site-packages\alembic\operations\toimpl.py", line 101, in create_table
  File "site-packages\alembic\ddl\impl.py", line 252, in create_table
  File "site-packages\alembic\ddl\impl.py", line 134, in _exec
  File "site-packages\sqlalchemy\engine\base.py", line 1014, in execute
  File "site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1076, in _execute_ddl
  File "site-packages\sqlalchemy\engine\base.py", line 1318, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1512, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1278, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table hashes already exists
[SQL:
CREATE TABLE hashes (
        id INTEGER NOT NULL,
        file_id VARCHAR,
        full_hash VARCHAR,
        p1 VARCHAR,
        p2 VARCHAR,
        p3 VARCHAR,
        p4 VARCHAR,
        PRIMARY KEY (id),
        FOREIGN KEY(file_id) REFERENCES files (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Failed to upgrade database!
Rolled back file: Z:\Downloads\manifest.sqlite   From: Z:\Downloads\manifest.sqlite-bkup.sqlite
```

**Comment by shadowmoose** [comment]
This seems like a database issue. Delete the manifest file created in the download directory; That should fix the problem.

**Comment by parasiteoflife** [comment]
Thanks. After deleting the file it now downloads fine. Why did the db corrupted? As I said this was the first time using this program so I suppose the db was created the moment I clicked Start downloading, right? Will try with some other subs to see if this happens again.
One question, does this downloads imgur albums inside a subfolder with the filename pattern we selected?

**Comment by parasiteoflife** [comment]
After adding more subs into another group this didn't happen again so I'm closing this. I'm now using you app, its working great so far, I'm coming from another app and after customizing the filename pattern is all good as it isn't re-downloading the same files.

A side question, if I have downloaded the Windows build from the releases section from where does RMD uses youtube-dl? I know it is using it because I'm getting some of this:
```
YTDL: ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
But I don't know which executable is using.

**Comment by shadowmoose** [comment]
Hey thanks for the feedback, I'm still looking into handling possible db corruption issues better. The YTDL library is native to python, so it is packed inside the source code.
