### ISSUE TITLE
AttributeError: 'submission' object has no attribute 'author'

### ISSUE THREAD

**Issue by albyofdoom** [shadowmoose/RedditDownloader#167]
### Describe the bug
When attempting to access/download posts in the r/promos subreddit (example below) RMD throws an exception. I was able to narrow it down to specific URL(s), and then confirmed by importing a csv with just those URL present.

### Environment Info
 - **OS:** Windows 10 2004 (OS Build 19041.508)
 - **RMD Version:** 3.1.0 
 - **Python Version:** Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32

### Screenshots/Information
URL(s): 
https://www.reddit.com/r/promos/comments/otfrw/spawn_creator_todd_mcfarlane_lends_his_talents_to/
https://www.reddit.com/r/promos/comments/pu3u6/50_hot_clothing_accidents_nsfw/
https://www.reddit.com/r/promos/comments/qt10t/okay_reddit_we_all_know_climate_change_is_real/
https://www.reddit.com/r/promos/comments/qzxgp/a_kochfunded_lobbying_campaign_could_go_down_in/

Output from bash console (personal info redacted):
```
***@***MINGW64 /d/archive/RedditDownload/_exports/export_***_20200925
$ C:/Users/***/AppData/Local/Programs/Python/Python37-32/python.exe "d:/gitrepo/RMD/Run.py" --import_csv="post_votes.csv"

Remaining: 0/0+

File: None
  Handler: None
   Status:


File: None
  Handler: None
   Status:


File: None
  Handler: None
   Status:


File: None
  Handler: None
   Status:


File: None
  Handler: None
   Status:


File: None
  Handler: None
   Status:



  File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "d:\gitrepo\RMD\redditdownloader\processing\redditloader.py", line 30, in run
    self.load()
  File "d:\gitrepo\RMD\redditdownloader\processing\redditloader.py", line 51, in load
    self._scan_sources()
  File "d:\gitrepo\RMD\redditdownloader\processing\redditloader.py", line 65, in _scan_sources
    for r in source.get_elements():
  File "d:\gitrepo\RMD\redditdownloader\sources\direct_file_source.py", line 39, in get_elements
    for e in self.get_subs(subs):
  File "d:\gitrepo\RMD\redditdownloader\sources\direct_file_source.py", line 63, in get_subs
    p = RedditElement(post)
  File "d:\gitrepo\RMD\redditdownloader\processing\wrappers\redditelement.py", line 39, in __init__
    self.detect_type(obj)

  File "d:\gitrepo\RMD\redditdownloader\processing\wrappers\redditelement.py", line 60, in detect_type
    self._ps_submission(obj)
Remaining: 0/0+  File "d:\gitrepo\RMD\redditdownloader\processing\wrappers\redditelement.py", line 143, in _ps_submission
    if post.author is None or post.author == '[deleted]':
Traceback (most recent call last):
AttributeError: 'submission' object has no attribute 'author'

File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status: Finished.


File: None
  Handler: None
   Status:

All finished.
***@***MINGW64 /d/archive/RedditDownload/_exports/export_***_20200925
$
```

### Additional context
RMD is operating normally otherwise. Have downloaded a few thousand other posts from the same timeframe without issue.

**Comment by shadowmoose** [comment]
Thanks for this detailed report, and the extra information you included.
I'll look into this soon, as I suspect an update to PRAW is in order due to recent Reddit changes.
