### ISSUE TITLE
RedditDownloader crashes when trying to rip a post with a long title

### ISSUE THREAD

**Issue by GreysenEvans** [shadowmoose/RedditDownloader#17]
Unfortunately, right in the middle of a 17,000+ post rip, RedditDownloader failed out with this error:

`Traceback (most recent call last):
  File "main.py", line 175, in <module>
    p = Scraper(settings, custom_settings)
  File "main.py", line 105, in __init__
    self.processor.run()
  File "./classes\elementprocessor.py", line 35, in run
    self.process_ele(ele)
  File "./classes\elementprocessor.py", line 60, in process_ele
    file_path = self.process_url(url, file_info)
  File "./classes\elementprocessor.py", line 73, in process_url
    ret = h.handle(url, info)
  File "./classes/handlers\imgur.py", line 276, in handle
    downloader.save_images(targ_dir)
  File "./classes/handlers\imgur.py", line 135, in save_images
    os.makedirs(album_folder)
  File "E:\Program Files\Python\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect`

The post that it was trying to scrape before it crashed had a very long name, and I suspect that this was the problem.

**Comment by shadowmoose** [comment]
Interesting bug. I overlooked the potential for a Reddit title (or combo of data) to turn out a longer filename than Windows supports. 

I'm not entirely sure the best approach to fix this, but I'll do some research and roll out something in the next update to condense filenames that are simply too long to save normally.
