### ISSUE TITLE
error running 3.1.4 (macos big sur)

### ISSUE THREAD

**Issue by WhyEssEff** [shadowmoose/RedditDownloader#195]
Traceback (most recent call last):
  File "Run.py", line 177, in <module>
  File "__main__.py", line 74, in run
  File "static/settings.py", line 58, in load
  File "static/settings.py", line 41, in from_json
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 2 (char 95)

**Comment by shadowmoose** [comment]
This seems like a malformed JSON configuration - have you run RMD before this error? If not, I'm not sure about the Big Sur architecture - it may not be fully supported.
