### ISSUE TITLE
AttributeError: 'submission' object has no attribute 'media_metadata'

### ISSUE THREAD

**Issue by WhyEssEff** [shadowmoose/RedditDownloader#198]
### Describe the bug
Downloader starts up then suddenly halts. 

Started downloader.
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Unable to parse URL from praw reddit album
Process RedditElementLoader:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "processing/redditloader.py", line 30, in run
  File "processing/redditloader.py", line 51, in load
  File "processing/redditloader.py", line 65, in _scan_sources
  File "sources/pushshift_subreddit.py", line 24, in get_elements
  File "processing/wrappers/redditelement.py", line 39, in __init__
  File "processing/wrappers/redditelement.py", line 60, in detect_type
  File "processing/wrappers/redditelement.py", line 158, in _ps_submission
AttributeError: 'submission' object has no attribute 'media_metadata'

### Environment Info
 - MacOS Big Sur Latest
 - RMD Version: 3.1.4

**Comment by shadowmoose** [comment]
Interesting... seems like RMD's getting some bad data from PushShift. I'll take a look.

**Comment by florianperrotti** [comment]
FYI I Encountered the exact same problem

**Comment by wormley** [comment]
I'm seeing a similar issue:
  File "reddit/RedditDownloader/redditdownloader/processing/wrappers/redditelement.py", line 133, in _submission
    for k, img in post.media_metadata.items():
AttributeError: 'NoneType' object has no attribute 'items'

In my case I just moved the "try:" at line 134 up before the "for" so at least the error is caught and ignored.

**Comment by shadowmoose** [comment]
I've pushed an update that should resolve this for the Python version. In the future, this will be completely fixed with the shift to the JS-based code, which uses an entirely new Reddit library.

Feel free to reopen this if anybody's experiencing any further issues with albums.
