### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by WhyEssEff** [shadowmoose/RedditDownloader#202]
### Describe the bug
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/psaw/PushshiftAPI.py", line 184, in _get
    response = requests.get(url, params=payload, proxies=self.proxies)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/WhyEssEff/Downloads/RedditDownloader-master/redditdownloader/processing/redditloader.py", line 30, in run
    self.load()
  File "/Users/WhyEssEff/Downloads/RedditDownloader-master/redditdownloader/processing/redditloader.py", line 51, in load
    self._scan_sources()
  File "/Users/WhyEssEff/Downloads/RedditDownloader-master/redditdownloader/processing/redditloader.py", line 65, in _scan_sources
    for r in source.get_elements():
  File "/Users/WhyEssEff/Downloads/RedditDownloader-master/redditdownloader/sources/pushshift_subreddit.py", line 23, in get_elements
    for post in ps.search_submissions(**_params):
  File "/usr/local/lib/python3.9/site-packages/psaw/PushshiftAPI.py", line 230, in _search
    for response in self._handle_paging(url):
  File "/usr/local/lib/python3.9/site-packages/psaw/PushshiftAPI.py", line 215, in _handle_paging
    yield self._get(url, self.payload)
  File "/usr/local/lib/python3.9/site-packages/psaw/PushshiftAPI.py", line 188, in _get
    log.debug("Connection error caught, retrying. Connection attempts so far: %s" % i+1)
TypeError: can only concatenate str (not "int") to str

### Environment Info
 - **OS:** Mac Big Sur Latest
 - **RMD Version:** 3.1.5

### Screenshots/Information
If applicable, add screenshots (or copies of error printouts) to help explain your problem.
[Include links to failed URLs/Posts, names of Sources, or other useful info here]

### Additional context
[Add any other context about the problem here.]

**Comment by shadowmoose** [comment]
Interesting, this seems to be an issue within the PushShift library RMD uses. The root cause seems to be a failure to connect to the PushShift website. I'll have to look into this one.
