### ISSUE TITLE
An invalid value was specified for display_name

### ISSUE THREAD

**Issue by SillySoon** [shadowmoose/RedditDownloader#204]
**Describe the bug**
Stops after starting Download

**Environment Info**
 - **OS:** Windows 10 Pro - 19042.928
 - **RMD Version:** Reddit Media Downloader 3.1.5

**Screenshots/Information**
```
Process RedditElementLoader:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "processing\redditloader.py", line 30, in run
  File "processing\redditloader.py", line 51, in load
  File "processing\redditloader.py", line 65, in _scan_sources
  File "sources\subreddit_posts_source.py", line 16, in get_elements
  File "static\praw_wrapper.py", line 131, in subreddit_posts
  File "praw\models\helpers.py", line 190, in __call__
  File "praw\models\reddit\subreddit.py", line 560, in __init__
  File "praw\models\listing\mixins\subreddit.py", line 71, in __init__
  File "praw\models\reddit\base.py", line 66, in __init__
ValueError: An invalid value was specified for display_name. Check that the argument for the display_name parameter is not empty.
YTDL: ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. [https://gfycat.com/unselfisheducatedgenet]
```

**Additional context**
- Have round about 200 Subreddits in it, maybe some issues with that?
- Cant type in consol cause of Windows i guess?

**Comment by SillySoon** [comment]
Kinda solved the problem, just failed to enter a subreddit qwq
