### ISSUE TITLE
Received 400 HTTP response

### ISSUE THREAD

**Issue by KaunWho** [shadowmoose/RedditDownloader#217]
The downloading never completes post an error. Not sure what the error is, I've provided the error text below.

Windows RMD 3.1.5

Process RedditElementLoader:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "processing\redditloader.py", line 30, in run
  File "processing\redditloader.py", line 51, in load
  File "processing\redditloader.py", line 65, in _scan_sources
  File "sources\subreddit_posts_source.py", line 16, in get_elements
  File "static\praw_wrapper.py", line 23, in wrapper
  File "static\praw_wrapper.py", line 67, in login
  File "praw\models\user.py", line 153, in me
  File "praw\reddit.py", line 566, in get
  File "praw\reddit.py", line 672, in _objectify_request
  File "praw\reddit.py", line 855, in request
  File "prawcore\sessions.py", line 331, in request
  File "prawcore\sessions.py", line 230, in _request_with_retries
  File "prawcore\sessions.py", line 189, in _make_request
  File "prawcore\rate_limit.py", line 33, in call
  File "prawcore\sessions.py", line 277, in _set_header_callback
  File "prawcore\auth.py", line 255, in refresh
  File "prawcore\auth.py", line 155, in _request_token
  File "prawcore\auth.py", line 38, in _post
prawcore.exceptions.ResponseException: received 400 HTTP response

**Comment by shadowmoose** [comment]
It seems like you're having issues connecting to Reddit in order to log in through RMD. Are you able to access the site itself?

**Comment by KaunWho** [comment]
Yeah, no issues accessing reddit via the browser and mobile. I reauthorized RMD and it seems to have been the fix. Apologies for the noob issue. Closing the issue now!
