### ISSUE TITLE
Download logic seems to expect Windows?

### ISSUE THREAD

**Issue by parkerlreed** [shadowmoose/RedditDownloader#23]
(To get this running I quickly updated my 2FA code in the setting.json, saved, and ran the script)

````
[parker@inspiron15 RedditDownloader]$ python main.py 

====================================
    Reddit Media Downloader 2.0
====================================
    (By ShadowMoose @ Github)

Loading all settings from file.
Loaded Source:  Source1
Authenticating via OAuth...
Authenticated as [parkerlreed]

Downloading from Source: Source1
Element loading complete.

Loaded handlers:  imgur, github, reddit, ytdl, newspaper
Loaded handlers:  imgur, github, reddit, ytdl, newspaper
Loaded handlers:  imgur, github, reddit, ytdl, newspaper
Loaded handlers:  imgur, github, reddit, ytdl, newspaper
Loaded handlers:  imgur, github, reddit, ytdl, newspaper
Traceback (most recent call last):
  File "main.py", line 228, in <module>
    p.run()
  File "main.py", line 124, in run
    self.processor.run()
  File "./classes/processing/elementprocessor.py", line 40, in run
    self.redraw(clear, q)
  File "./classes/processing/elementprocessor.py", line 92, in redraw
    print(out.rstrip(), end='')
  File "/usr/lib/python3.6/site-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/lib/python3.6/site-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/usr/lib/python3.6/site-packages/colorama/ansitowin32.py", line 167, in write_and_convert
    self.convert_ansi(*match.groups())
  File "/usr/lib/python3.6/site-packages/colorama/ansitowin32.py", line 181, in convert_ansi
    self.call_win32(command, params)
  File "/usr/lib/python3.6/site-packages/colorama/ansitowin32.py", line 212, in call_win32
    winterm.erase_screen(params[0], on_stderr=self.on_stderr)
AttributeError: 'NoneType' object has no attribute 'erase_screen'
````

**Comment by shadowmoose** [comment]
Hmm, interesting... The console formatting library seems to be trying to reference a character (one used to clear the terminal) that it doesn't have. It's been tested on Win/Ubuntu, but there are probably unforeseen issues that vary with the terminal.

At any rate, I know what's happening here. I'll roll out a fix for this problem in a bit.

**Comment by parkerlreed** [comment]
Haha nice

````
python main.py > test.txt
````

Another terminal
````
tail -f test.txt
````

Works

**Comment by parkerlreed** [comment]
Multi threading working nicely!

**Comment by shadowmoose** [comment]
This should be patched on the live branch, pending testing, and will be rolled out officially in the next release soon.

**Comment by parkerlreed** [comment]
Works!
