### ISSUE TITLE
Error importing csv from GDPR export

### ISSUE THREAD

**Issue by Cealor** [shadowmoose/RedditDownloader#255]
### Describe the bug
Running `python redditdownloader --import_csv="saved_posts.csv" --full_csv` with a csv from the Reddit GDPR export throws KeyError.

### Environment Info
 - **OS:** MacOS 12.4
 - **RMD Version:** 3.1.5

### Screenshots/Information

```
Process RedditElementLoader:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/user/RedditDownloader-master/redditdownloader/processing/redditloader.py", line 30, in run
    self.load()
  File "/Users/user/RedditDownloader-master/redditdownloader/processing/redditloader.py", line 51, in load
    self._scan_sources()
  File "/Users/user/RedditDownloader-master/redditdownloader/processing/redditloader.py", line 65, in _scan_sources
    for r in source.get_elements():
  File "/Users/user/RedditDownloader-master/redditdownloader/sources/direct_file_source.py", line 29, in get_elements
    if row['direction'] == 'up':
KeyError: 'direction'
```

### Additional context
post_votes.csv works fine, but doesn't update the download handler:

```
Remaining: 0/0+

File: None
  Handler: None
   Status: Starting up...


File: None
  Handler: None
   Status: Starting up...


File: None
  Handler: None
   Status: Starting up...


File: None
  Handler: None
   Status: Starting up...


File: None
  Handler: None
   Status: Starting up...
```

**Comment by tonylaw7** [comment]
Was this fixed? I'm experiencing the same bug with GDPR export as well.
