### ISSUE TITLE
Error during setup after Authentication

### ISSUE THREAD

**Issue by arlojeremy** [shadowmoose/RedditDownloader#54]
After going through the setup, it said: Authenticated as [username]

And then the following error:

`Traceback (most recent call last):
  File "main.py", line 175, in <module>
    p = Scraper(settings, custom_settings)
  File "main.py", line 66, in __init__
    self.settings = Settings(settings_file, can_save=(c_settings is None), can_load=(not args.test) )
  File "./classes\settings.py", line 42, in __init__
    wizard.run(file)
  File "./classes/wizards\wizard.py", line 69, in run
    "user_agent": "RMD-"+random.random(),
TypeError: must be str, not float`

After running `python main.py` again after this error:

`Using file values.
Authenticating via OAuth...
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    p = Scraper(settings, custom_settings)
  File "main.py", line 95, in __init__
    reddit.login()
  File "./classes\reddit.py", line 36, in login
    _user = _reddit.user.me()
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\models\user.py", line 99, in me
    user_data = self._reddit.get(API_PATH['me'])
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\reddit.py", line 408, in get
    data = self.request('GET', path, params=params)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\reddit.py", line 534, in request
    params=params)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 185, in request
    params=params, url=url)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 116, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 101, in _make_request
    params=params)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\rate_limit.py", line 35, in call
    kwargs['headers'] = set_header_callback()
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 145, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\auth.py", line 328, in refresh
    password=self._password)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Arlo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response`

Thanks

**Comment by shadowmoose** [comment]
Odd, that bug has been fixed for over a year. What version of RMD are you running?

**Comment by arlojeremy** [comment]
Oooof. Sorry, it was late last night and somehow I ended up with zip of 1.5. I zipped up the current master (3.0) to try and it starts fine, but trying to open in any mode (chrome, browser or manually putting in the link) just loads up a blank page, which seems similar to [this issue.](https://github.com/shadowmoose/RedditDownloader/issues/53).

I'll close this one. Thank you.
