### ISSUE TITLE
Trouble installing - python woes

### ISSUE THREAD

**Issue by Saortica** [shadowmoose/RedditDownloader#92]
EDIT:
Worked out that the latest version of Python, 3.8.0 is incompatible with installing Pillow 6.2.0. And Pillow 6.2.1, which installs on Python 3.8.0, is incompatible with RDM.

I'm in the process of downgrading my python, but now appear to be having troubles with beautiful soup. I'll see how I go.

EDIT 2:
All installed and webui loading.

**Comment by Saortica** [comment]
I tried renaming Pillow==6.2.0 to Pillow==6.2.1 and tried the command line install again. It appeared to get through everything else without a problem. However, when I ran run.py I got:

```
C:\Program Files More\RedditDownloader>run.py
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Updating requirements. This may take a while on first-time installs..
Requirements up to date!
Traceback (most recent call last):
  File "C:\Program Files More\RedditDownloader\Run.py", line 78, in <module>
    import redditdownloader.__main__ as rmd
  File "C:\Program Files More\RedditDownloader\redditdownloader\__main__.py", line 10, in <module>
    from interfaces.terminal import TerminalUI
  File "C:\Program Files More\RedditDownloader\redditdownloader\interfaces\terminal.py", line 2, in <module>
    from processing.controller import RMDController
  File "C:\Program Files More\RedditDownloader\redditdownloader\processing\controller.py", line 8, in <module>
    from processing.post_processing import Deduplicator
  File "C:\Program Files More\RedditDownloader\redditdownloader\processing\post_processing.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'


Caught a fatal error running RMD. Cannot continue.
-Press [Enter] to quit-
```

So I'm guessing something changed between Pillow 6.2.0 and Pillow 6.2.1, and I need to work out how to get 6.2.0 on the system?

**Comment by shadowmoose** [comment]
I'm going to assume the install worked for you, and close this issue. If you're still having trouble with RMD, feel free to reopen.
